### ISSUE TITLE
开发者你好。

### ISSUE THREAD

**Issue by datidu** [Tokinx/McBlog#3]
我在使用过程中上传至网页目录后。进入后台自动跳转至
http://www.lnmp.org/mc-admin/post.php
权限什么的也设置过了 但是始终无法访问后台。

**Comment by Tokinx** [comment]
mc-files/mc-conf.php，这个文件，你看一看site_link有没有正确配置

**Comment by datidu** [comment]
'site_link' => 'www.datidu.cc',
是这样设置的吧？  依然跳转。

**Comment by Tokinx** [comment]
'site_link' => 'http://www.datidu.cc',

**Comment by Tokinx** [comment]
很抱歉给您带来的困惑，我会想办法再降低使用难度，不好意思

**Comment by datidu** [comment]
QAQ    真不好意思  是自己太蠢！ 谢谢了。

**Comment by datidu** [comment]
修改之后  进入后台的跳转问题依然存在！

**Comment by Tokinx** [comment]
临时的解决方法就是你先登录，然后访问http://你的域名/mc-admin/ ，我会排查一下问题，尽快修复

**Comment by hnwy** [comment]
我扔到手机上正常，手机安装ksweb，后台能打开，没有跳转。我猜是不是PHP和nginx要做什么设置。
不过关于页面会出现  “Notice: unserialize(): Error at offset 394 of 395 bytes in /storage/sdcard0/htdocs/index.php on line 142”，编辑“关于”会出现“Notice: unserialize(): Error at offset 394 of 395 bytes in /storage/sdcard0/htdocs/mc-admin/page-edit.php on line 130”。而且不能添加页面。
另，如何获取多说代码的ID、标题、网址？

太牛逼了，同时支持富文本编辑和MD编辑。

**Comment by Tokinx** [comment]
@hnwy 不知道出现问题的是什么环境，正常情况下，购买虚拟主机使用mcblog是不会出现问题的，演示站可以体验一下。不建议使用一些比较极端的环境，当然欢迎你提出的问题，我也会想办法解决。

需要去多说官网申请账号获取评论代码。

**Comment by hnwy** [comment]
哦，是小内存的VPS，安装lnmp。最近128M、64M的小内存比较火，你懂得，于是不少人打算再搭建个博客。
期待beta2
