### ISSUE TITLE
多说评论如何插入

### ISSUE THREAD

**Issue by hnwy** [Tokinx/McBlog#4]
多说评论的data-title和data-url应该怎么填，我分别填的<?php mc_the_title(); ?>和<?php mc_the_url(); ?>，仍然不能正确加载

**Comment by hnwy** [comment]
搞定

`<div class="ds-thread"></div>
<script type="text/javascript">
var duoshuoQuery = {short_name:"这里换成你的多说域名"};
	(function() {
		var ds = document.createElement('script');
		ds.type = 'text/javascript';ds.async = true;
		ds.src = 'http://static.duoshuo.com/embed.js';
		ds.charset = 'UTF-8';
		(document.getElementsByTagName('head')[0] 
		|| document.getElementsByTagName('body')[0]).appendChild(ds);
	})();
	</script>`

**Comment by Tokinx** [comment]
这个就是用js获取文章的链接、标题吧，不是用的php，理论适用于所有程序

**Comment by Tokinx** [comment]
非常感谢你提供的方法

**Comment by hnwy** [comment]
获取到的Thread Key，是只有多说能理解的字符。该方法是miniblog下插入多说的代码，放到mcblog上也成了
