### ISSUE TITLE
我想做个模板，但是不知道怎么获取文章第一张图片到列表页

### ISSUE THREAD

**Issue by ichizi** [Tokinx/McBlog#5]
列表页我想做成图文形式，求教作者，如何把文章的第一张图片取到列表页？或者有其他什么办法能够在列表页取一张图片

**Comment by Tokinx** [comment]
程序是有获取第一张图的代码的，具体怎么调用可以参考我已经做的主题：
https://github.com/Tokinx/Themes/tree/master/Mc-Themes

**Comment by Tokinx** [comment]
<?php mc_the_thumbnail();?>
