### ISSUE TITLE
unserialize() 函数报错

### ISSUE THREAD

**Issue by Echowxsy** [Tokinx/McBlog#8]
在访问 `localhost/?about/` 的时候会出现错误提示
> Notice: unserialize(): Error at offset 201 of 409 bytes in C:\USBWebser_8.6\root\index.php on line 140

**Comment by Tokinx** [comment]
请切换php版本，当前php版本不支持unserialize()函数。
建议使用其它一键包，不要用USBWebser，如PHPstudy
